#!/bin/bash
#SBATCH --job-name=gpumonty
#SBATCH -c 1
#SBATCH -G 1
#SBATCH --partition=dev
#SBATCH --time=00:05:00
#SBATCH --gpu_cmode=exclusive
# Load necessary modules
module load cuda/12.4.0
module load gsl

# Query available clock speeds


# Lock GPU clocks (use a suitable range for your A30)

# Run your program
#ncu --clock-control none --set full --export analysis_sherlock2 ./gpumonty 5000000 ./data/dump019 sane
./gpumonty 5000000 ./data/dump019 sane