#!/bin/bash
#SBATCH --job-name=gpumonty_run
#SBATCH --partition=ampere
#SBATCH --time=7-00:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=40
#SBATCH --gres=gpu:1
#SBATCH --mem=0          # Use all memory on the node (optional)
#SBATCH --output=gpumonty_%j.out
#SBATCH --error=gpumonty_%j.err

# Load required modules
module load cuda
module load hdf5
module load gsl

# Set OpenMP thread count
export OMP_NUM_THREADS=40

# Run your GPU code
./gpumonty 1e6 ./data/sample_dump_SANE_a+0.94_MKS_0900.h5 sane_ben.spec

