/*
 * GPUmonty - metrics.h
 * Copyright (C) 2026 Pedro Naethe Motta
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>.
 */
/*
Declarations of the functions in the metrics.cu file
*/


/**
 * @brief Macro to enable or disable the computation of the inverse metric using LU decomposition.
 * 
 * if set to 1, the code will compute the inverse metric \f$ g^{\mu\nu} \f$ through LU decomposition and substitution.
 * if set to 0, the code will use the kerr analytical expressions for the inverse metric.
 */
#define FIND_GCON_MATRIX_INV (1)


#ifndef METRICS_H
#define METRICS_H

/**
 * @brief Calculates the square root of the absolute determinant of the metric tensor, \f$ \sqrt{-g} \f$.
 
 * @details 
 * - **General Case**: Uses GSL-based LU decomposition to compute the determinant of the covariant metric \f$ g_{\mu\nu} \f$.
 * - **Simplified Case**: If `SPHERE_TEST` is defined, it assumes a diagonal metric for faster computation.
 * 
 * @param gcov The covariant metric tensor \f$ g_{\mu\nu} \f$.
 * 
 * @return The value of \f$ \sqrt{| \det(g_{\mu\nu}) |} \f$.
 */
__host__ double gdet_func(double gcov[][NDIM]);

/**
 * @brief Performs in-place LU decomposition with partial pivoting and row-wise normalization.
 * * This function factorizes a square matrix \f$ A \f$ into a lower triangular matrix \f$ L \f$ and 
 * an upper triangular matrix \f$ U \f$ such that \f$ PA = LU \f$. Then it can be used to solve linear systems or invert matrices.
 *
 * @param A The \f$ \rm{NDIM} \times \rm{NDIM} \f$ matrix to decompose (modified in-place).
 * @param permute Array to store the row permutation indices (pivoting history).
 * 
 * @return Returns 0 for success, 1 if the matrix is singular.
 */
__host__  __device__ int LU_decompose( double A[][NDIM], int permute[] );

/**
 * @brief Solves a linear system \f$ Ax = B \f$ using forward and backward substitution.
 * * This function takes the results of `LU_decompose` (an in-place LU matrix and a 
 * permutation vector) and solves for the vector \f$ B \f$. It is primarily used 
 * in the simulation to invert the metric tensor \f$ g_{\mu\nu} \f$ to find its 
 * contravariant form \f$ g^{\mu\nu} \f$.
 *
 * @details 
 * - **Permutation**: Swaps elements of \f$ B \f$ to match the partial pivoting order recorded in `permute`.
 * - **Forward Substitution**: Solves the lower triangular system \f$ Ly = Pb \f$. Since the diagonal 
 * elements of \f$ L \f$ are implicitly 1, no division is required.
 * - **Backward Substitution**: Solves the upper triangular system \f$ Ux = y \f$, utilizing the 
 * diagonal elements of \f$ U \f$ stored in `A[i][i]`.
 * * @param A The \f$ \rm{NDIM} \times \rm{NDIM} \f$ LU-decomposed matrix.
 * @param B The right-hand side vector (replaced by the solution vector \f$ x \f$ in-place).
 * @param permute The permutation array generated by `LU_decompose`.
 * 
 * @return void
 */
__host__ __device__ void LU_substitution( double A[][NDIM], double B[], int permute[] );


/**
 * @brief Computes the inverse of a square matrix unifying the usage of `LU decomposition` and `substitution`.
 *
 * This function calculates the inverse of an \f$ NDIM \times NDIM \f$ matrix (typically 
 * the covariant metric \f$ g_{\mu\nu} \f$ to obtain the contravariant metric \f$ g^{\mu\nu} \f$). 
 * It solves the matrix equation \f$ A \cdot A^{-1} = I \f$ by treating each column of the 
 * identity matrix \f$ I \f$ as a separate linear system.
 *
 *
 * @param Am The input \f$ NDIM \times NDIM \f$ matrix to be inverted.
 * @param Aminv The output matrix where the calculated inverse is stored.
 * 
 * @return 0 for success; 1 if the matrix is singular or contains invalid values.
 */
__host__ __device__ int invert_matrix( double Am[][NDIM], double Aminv[][NDIM] )  ;

/**
 * @brief Computes the contravariant metric tensor \f$ g^{\mu\nu} \f$ using either numerical inversion or analytical expressions.
 * * This function provides the inverse of the metric tensor at a specific 4-position \f$ X^\mu \f$. It supports 
 * a toggle between a general-purpose numerical solver and optimized analytical formulas for specific 
 * spacetimes.
 *
 * if `FIND_GCON_MATRIX_INV` is defined:
 * - Calls `invert_matrix()` to perform a full LU decomposition on \f$ g_{\mu\nu} \f$. This is the 
 * most flexible method and works for any metric, but is computationally more expensive.
 * 
 * **Path B: Analytical/Hardcoded** (Default):
 * - SPHERE_TEST: Returns a simple diagonal inverse for flat space in spherical coordinates.
 * - Modified Kerr-Schild (MKS): Computes exact contravariant components for a rotating Kerr 
 * black hole.
 * 
 * @param X The 4-position \f$ X^\mu \f$ in code coordinates.
 * @param gcov The covariant metric tensor \f$ g_{\mu\nu} \f$ (used for numerical inversion or diagonal tests).
 * @param gcon Output: The calculated contravariant metric tensor \f$ g^{\mu\nu} \f$.
 * 
 * @return void
 */
__host__ __device__ void gcon_func(const double X[4], double gcov[][NDIM], double gcon[][NDIM]);

/**
 * @brief Computes the Christoffel symbols (\f$ \Gamma^i_{jk} \f$) analytically for the coodinate system MKS.
 * 
 * @param X 4-position \f$ X^\mu \f$ in code coordinates.
 * @param lconn A 3D array `[4][4][4]` populated with the connection coefficients.
 * 
 * @note This function has been tested against finite differences.
 * 
 * @return void   
 */
__device__ void ConnectionAnalyticalMKS(const double X[4], double lconn[4][4][4]);

/**
 * @brief Wrapper function to compute the Christoffel symbols (\f$ \Gamma^i_{jk} \f$) based on the selected metric type.
 * 
 * @param X 4-position \f$ X^\mu \f$ in code coordinates.
 * @param lconn A 3D array `[4][4][4]` populated with the connection coefficients.
 * 
 * @return void
 */
__device__ void ConnectionAnalyticalWrapper(const double X[4], double lconn[4][4][4]);

/**
 * @brief Computes the Christoffel symbols (\f$ \Gamma^i_{jk} \f$) analytically for the coodinate system MKS3.
 * 
 * @param X 4-position \f$ X^\mu \f$ in code coordinates.
 * @param lconn A 3D array `[4][4][4]` populated with the connection coefficients.
 * 
 *  @note This function has been tested against finite differences.
 * 
 * @return void   
 */
__device__ void ConnectionAnalyticalMKS3(const double X[4], double lconn[4][4][4]);

/**
 * @brief Lowers the index of a contravariant 4-vector to its covariant form.
 * * This function performs the metric mapping \f$ u_\mu = g_{\mu\nu} u^\nu \f$. It effectively 
 * transforms a vector from the tangent space to the cotangent space (one-form) 
 * using the local covariant metric tensor.
 * 
 * @param ucon Input contravariant 4-vector \f$ u^\nu \f$.
 * @param Gcov Input covariant metric tensor \f$ g_{\mu\nu} \f$.
 * @param ucov Output covariant 4-vector \f$ u_\mu \f$.
 * 
 * @return void
 */
__host__ __device__ void lower(double *ucon, const double Gcov[NDIM][NDIM], double *ucov);
#endif
