name: gpumonty tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install CUDA
        run: |
          sudo apt-get update
          sudo apt-get install -y nvidia-cuda-toolkit

      - name: Install Python deps
        run: |
          pip install numpy scipy astropy matplotlib

      - name: Compile
        run: |
          make CUDA_PATH=/usr -j$(nproc)
          make clean
          make -j 12

      - name: Run tests
        run: |
          python3 tests-ci/run_ci_tests.py